{{- $name := include "chat-web-api.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "chat-web-api.name" . }}
    chart: {{ template "chat-web-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ApplicationInsights__ConnectionString: {{ .Values.applicationInsights.connectionString | b64enc }}