apiVersion: v1
kind: Secret
metadata:
  name: "secret-api"
  labels:
    app: api
type: Opaque
stringData:
  MSCosmosDBOpenAI__CognitiveSearch__Endpoint: '{{.Env.AZURE_COGNITIVE_SEARCH_ENDPOINT}}'
  MSCosmosDBOpenAI__CognitiveSearch__Key: '{{.Env.AZURE_COGNITIVE_SEARCH_KEY}}'
  MSCosmosDBOpenAI__OpenAI__Endpoint: '{{.Env.AZURE_OPENAI_ENDPOINT}}'
  MSCosmosDBOpenAI__OpenAI__Key: '{{.Env.AZURE_OPENAI_KEY}}'
  MSCosmosDBOpenAI__CosmosDB__Endpoint: '{{.Env.AZURE_COSMOS_DB_ENDPOINT}}'
  MSCosmosDBOpenAI__CosmosDB__Key: '{{.Env.AZURE_COSMOS_DB_KEY}}'
  MSCosmosDBOpenAI__DurableSystemPrompt__BlobStorageConnection: '{{.Env.AZURE_STORAGE_CONNECTION_STRING}}'
  MSCosmosDBOpenAI__CognitiveSearchMemorySource__Endpoint: '{{.Env.AZURE_COGNITIVE_SEARCH_ENDPOINT}}'
  MSCosmosDBOpenAI__CognitiveSearchMemorySource__Key: '{{.Env.AZURE_COGNITIVE_SEARCH_KEY}}'
  MSCosmosDBOpenAI__CognitiveSearchMemorySource__ConfigBlobStorageConnection: '{{.Env.AZURE_STORAGE_CONNECTION_STRING}}'
  MSCosmosDBOpenAI__BlobStorageMemorySource__ConfigBlobStorageConnection: '{{.Env.AZURE_STORAGE_CONNECTION_STRING}}'
