apiVersion: v1
kind: Secret
metadata:
  name: "secret-api"
  labels:
    app: api
type: Opaque
stringData:
  MSCosmosDBOpenAI__AISearch__Endpoint: '{{.Env.AZURE_COGNITIVE_SEARCH_ENDPOINT}}'
  MSCosmosDBOpenAI__AISearch__Key: '{{.Env.AZURE_COGNITIVE_SEARCH_KEY}}'
  MSCosmosDBOpenAI__AISearchMemorySource__Endpoint: '{{.Env.AZURE_COGNITIVE_SEARCH_ENDPOINT}}'
  MSCosmosDBOpenAI__AISearchMemorySource__Key: '{{.Env.AZURE_COGNITIVE_SEARCH_KEY}}'
  MSCosmosDBOpenAI__AISearchMemorySource__ConfigBlobStorageConnection: '{{.Env.AZURE_STORAGE_CONNECTION_STRING}}'
  MSCosmosDBOpenAI__BlobStorageMemorySource__ConfigBlobStorageConnection: '{{.Env.AZURE_STORAGE_CONNECTION_STRING}}'
  MSCosmosDBOpenAI__CosmosDB__Endpoint: '{{.Env.AZURE_COSMOS_DB_ENDPOINT}}'
  MSCosmosDBOpenAI__CosmosDB__Key: '{{.Env.AZURE_COSMOS_DB_KEY}}'
  MSCosmosDBOpenAI__CosmosDBVectorStore__Endpoint: '{{.Env.AZURE_COSMOS_DB_VEC_ENDPOINT}}'
  MSCosmosDBOpenAI__CosmosDBVectorStore__Key: '{{.Env.AZURE_COSMOS_DB_VEC_KEY}}'
  MSCosmosDBOpenAI__DurableSystemPrompt__BlobStorageConnection: '{{.Env.AZURE_STORAGE_CONNECTION_STRING}}'
  MSCosmosDBOpenAI__OpenAI__Endpoint: '{{.Env.AZURE_OPENAI_ENDPOINT}}'
  MSCosmosDBOpenAI__OpenAI__Key: '{{.Env.AZURE_OPENAI_KEY}}'
