apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  annotations:
    azure.workload.identity/client-id:  {{ .Env.API_WORKLOADIDENTITY_CLIENT_ID }}
    azure.workload.identity/tenant-id: {{ .Env.AZURE_TENANT_ID }}
  labels:
    azure.workload.identity/use: "true"